### ISSUE TITLE
redmine:3.4 contains ruby-openid-2.3.0 which still uses unsupported Digest::HMAC

### ISSUE THREAD

**Issue by laf0rge** [docker-library/redmine#131]
The current redmine:3.4 image contains an ancient (2014!) version of ruby-openid: 2.3.0

That version still uses the deprecated Digest::HMAC API and will break if it's actually used. OpenSSL::HMAC is what should actually be used.  See https://apidock.com/ruby/Digest/HMAC

I had to apply the following patch as a quick hack to make it work: http://git.osmocom.org/docker-playground/tree/redmine/hmac.diff

The proper solution most likely entails to analyze why a 2014 version of ruby-openid is shipped, rather than any of the more recent versions.  current is 2.8.0.

**Comment by tianon** [comment]
This is something that comes directly from Redmine upstream's `Gemfile`, not something we explicitly install, so for this to be updated it needs to happen there first: https://github.com/redmine/redmine/blob/5533eeff239e024539f3ddd5b2ffe3528144beef/Gemfile#L35

```ruby
# Optional gem for OpenID authentication
group :openid do
  gem "ruby-openid", "~> 2.3.0", :require => "openid"
  gem "rack-openid"
end
```

https://www.redmine.org/issues/14919 is a related ticket, but it appears to be what got us to 2.3.0 (5 years ago, heh).

Closing, since there's nothing _we_ can do here, but I'd recommend following up with upstream (probably via an issue on their Trac instance?) to see if they're willing to bump this now. :+1:
