### ISSUE TITLE
Is there any way to enable HTTPS with certification?

### ISSUE THREAD

**Issue by shwneo** [docker-library/redmine#186]
Not even a word on this topic was given in the DockerHub's readme page.
Is it possible to give some hint somewhere in the doc thus I could enable HTTPS (of course with specific certifications, self-signed or CA-signed) in this docker image rather than learn Ruby on Rails from scratch?
The Redmine official guide is saying I can configure Redmine with Apache or Nginx, then I can establish SSL against the specific web server, but what the condition of the docker image? what webserver is the docker image using?

**Comment by wglambert** [comment]
These steps should work https://github.com/docker-library/redmine/issues/4#issuecomment-149335151

**Comment by shwneo** [comment]
@wglambert Thanks! That'll be very helpful!

**Comment by jeverling** [comment]
Hi, I use the excellent [https-portal](https://hub.docker.com/r/steveltn/https-portal/) Docker image as a reverse proxy. It's nginx based and handles letsencrypt for you.

You can just instruct it to serve your Redmine installation under https by including a mapping like this: `redmine.your-domain.com -> http://your-docker-ip:3000`.
I suggest to mount the volume where it writes the certificates to, so they don't get regenerated on each startup (you might get rate-limited by letsencrypt if that happens a lot otherwise).

Other popular options for this purpose are Traefik and caddy (I believe).
But https-portal works beautifully for me.
