### ISSUE TITLE
email configuration doesn't work

### ISSUE THREAD

**Issue by wilsonliyong** [docker-library/redmine#187]
I installed docker 4.1.0 and define the configuration.yml as below:
production:
    email_delivery:
      delivery_method: :smtp
      smtp_settings:
        address: "smtp.mxhichina.com"
        port: 465
        authentication: :login
        domain: 'smtp.mxhichina.com'
        user_name: 'xxx@sina.com'
        password: 'xxx'

then enter Administration->Settings->Email notifications, after press 'Send a test email' I got error as below:
    An error occurred while sending mail (end of file reached)
Where I can find detail error or how to fix it?

**Comment by wglambert** [comment]
Reproducing my comment from https://github.com/docker-library/redmine/issues/175#issuecomment-537702898:

I can't reproduce any issue with email.
Template email:
```
project: myproject
tracker: tracker
category:function
priority: high
status: Open
subject: subject
description: test
```

`configuration.yml` is the template from https://www.redmine.org/projects/redmine/wiki/EmailConfiguration#GMail-Google-Apps

On the web interface I populated the missing project, tracker, status, and priority when I got the error they were required
```console
$ docker run -d -v "$PWD"/configuration.yml:/usr/src/redmine/config/configuration.yml -p 3000:3000 --rm --name redmine redmine:4
e36dc26afc2bf70f0f46192c2057dd10ad024e0c9750cb3f9590f11115d28ce6

$ docker exec -it redmine bash

root@e36dc26afc2b:/usr/src/redmine# rake redmine:email:receive_imap unknown_user=accept no_permission_check=1 RAILS_ENV=production host=imap.gmail.com port=993 ssl=1 username="$email" password="$pass"
W, [2019-10-02T22:01:18.842276 #49]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2019-10-02T22:01:20.213460 #49]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
W, [2019-10-02T22:01:20.233041 #49]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
E, [2019-10-02T22:01:20.686401 #49] ERROR -- : MailHandler: Validation failed: Tracker cannot be blank, Priority cannot be blank, Status cannot be blank

root@e36dc26afc2b:/usr/src/redmine# rake redmine:email:receive_imap unknown_user=accept no_permission_check=1 RAILS_ENV=production host=imap.gmail.com port=993 ssl=1 username="$email" password="$pass"
W, [2019-10-02T22:02:21.695774 #53]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2019-10-02T22:02:23.071436 #53]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
W, [2019-10-02T22:02:23.084588 #53]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
I, [2019-10-02T22:02:23.518957 #53]  INFO -- : MailHandler: issue #1 created by Anonymous
```

There's also this issue with email and cron https://github.com/docker-library/redmine/issues/64

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by wilsonliyong** [comment]
Thanks for reply!

I also tested with gmail and it is ok. So I know the problem is mailbox 'smtp.mxhichina.com' , I guess it is free version and no support for sending on server.
