### ISSUE TITLE
Easy run in OpenShift

### ISSUE THREAD

**Issue by AleksdemSA** [docker-library/redmine#203]
Hello!
Can you add 2 simple commands to README to create a service in OpenShift?

```
oc new-project redmine
oc new-app https://github.com/docker-library/redmine.git --context-dir=4.1
```

This can be helpful to anyone.:)

**Comment by tianon** [comment]
Frankly this seems like pretty generic OpenShift documentation, so I'm not sure I understand why our image documentation would be an appropriate place for it?

(Even more especially since from the command you've given, it won't be using the images built/maintained as part of the official images process, but rather building new images directly from the `Dockerfile` source?)

**Comment by AleksdemSA** [comment]
You are right :)
