### ISSUE TITLE
Plugins in a Docker container

### ISSUE THREAD

**Issue by gexpult** [docker-library/redmine#212]
Hi,

I have Redmine in a Docker container. How can I install plugins? I tried one that use git and bundle, like this:
`git clone <URL>`
`bundle update`
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

I connected to a shell in the container and `git clone` worked but `bundle update` fails. It seems I need gcc to build part of this (nokogiri).

Is there an easier way to do this? Do I need to install gcc somehow?

**Comment by wglambert** [comment]
https://github.com/docker-library/redmine/issues/109#issuecomment-376341254

Here's an example https://github.com/docker-library/redmine/issues/81#issuecomment-335613338

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
