### ISSUE TITLE
Error not running redmine after installing CKeditor plugin on docker

### ISSUE THREAD

**Issue by kaaaq** [docker-library/redmine#214]
Hi
I want to install CKeditor as plugin for redmine on docker 
but after installation when i run docker-compose it stop in these step:
```
redmine_1  | The git source https://github.com/a-ono/rich.git is not yet checked out. Please
redmine_1  | run `bundle install` before trying to start your application
redmine_1  | Fetching https://github.com/a-ono/rich.git
```
My installation step:
```

1.
sudo docker exec -ti test_redmine_1 gosu redmine bash
2.
download and extract plugin in plugin directoty

3.
In the root directory:
bundle install --without development test
4.
rake redmine:plugins:migrate RAILS_ENV=production

```

Ckeditor version: 1.2.3
Redmin version: Redmine 4.1.1.stable
Docker CE and docker compose on  ubuntu 16.04

**Comment by wglambert** [comment]
If you could get a minimal reproducer that would help with probing around

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by gainskills** [comment]
Met a similar issue before, the root cause should be an incompatiable issue.
I figured the issue out by installing a new version CKEditor.
E.g.: https://github.com/lornwolf/redmine_ckeditor

**Comment by tianon** [comment]
Nice, glad you've found a solution :+1:

(I'm going to close because this now appears both resolved, and a better candidate for the support forums mentioned above.)
