### ISSUE TITLE
ticket creation via e-mail does not work

### ISSUE THREAD

**Issue by drhuh** [docker-library/redmine#217]
I try to fetch e-mails to create tickets, but regardless what I do, I only see a warning and no ticket is created. Here is my script:

    #!/bin/bash

    cd /tmp

    if [ ! -f .env ]; then
        echo "missing .env file"
        exit
    fi
    source .env

    rake --trace -f /usr/src/redmine/Rakefile redmine:email:receive_imap unknown_user=accept no_permission_check=1 RAILS_ENV="production" host=$host port=$port username=$user password=$pwd ssl=$ssl folder=Redmine move_on_failure="rmfailed"

The output is

    ** Invoke redmine:email:receive_imap (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    ** Execute redmine:email:receive_imap
    W, [2020-10-21T18:12:57.282029 #604]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.

What is going wrong here?

**Comment by wglambert** [comment]
That message is just a warning not an error, maybe it's an issue with your `host=$host` you could try it with `$host` in double quotes

Reproducing my comment from https://github.com/docker-library/redmine/issues/175#issuecomment-537702898:
I can't reproduce any issue with email.

Template email:
```
project: myproject
tracker: tracker
category:function
priority: high
status: Open
subject: subject
description: test
```

`configuration.yml` is the template from https://www.redmine.org/projects/redmine/wiki/EmailConfiguration#GMail-Google-Apps

On the web interface I populated the missing project, tracker, status, and priority when I got the error they were required
```console
$ docker run -d -v "$PWD"/configuration.yml:/usr/src/redmine/config/configuration.yml -p 3000:3000 --rm --name redmine redmine:4
e36dc26afc2bf70f0f46192c2057dd10ad024e0c9750cb3f9590f11115d28ce6

$ docker exec -it redmine bash

root@e36dc26afc2b:/usr/src/redmine# rake redmine:email:receive_imap unknown_user=accept no_permission_check=1 RAILS_ENV=production host=imap.gmail.com port=993 ssl=1 username="$email" password="$pass"
W, [2019-10-02T22:01:18.842276 #49]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2019-10-02T22:01:20.213460 #49]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
W, [2019-10-02T22:01:20.233041 #49]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
E, [2019-10-02T22:01:20.686401 #49] ERROR -- : MailHandler: Validation failed: Tracker cannot be blank, Priority cannot be blank, Status cannot be blank

root@e36dc26afc2b:/usr/src/redmine# rake redmine:email:receive_imap unknown_user=accept no_permission_check=1 RAILS_ENV=production host=imap.gmail.com port=993 ssl=1 username="$email" password="$pass"
W, [2019-10-02T22:02:21.695774 #53]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2019-10-02T22:02:23.071436 #53]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
W, [2019-10-02T22:02:23.084588 #53]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
I, [2019-10-02T22:02:23.518957 #53]  INFO -- : MailHandler: issue #1 created by Anonymous
```

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
