### ISSUE TITLE
Issues with A-Common-Libs

### ISSUE THREAD

**Issue by RolandSM** [docker-library/redmine#240]
Hello,

I post here an external plugin issue, because I think its a specific docker thing.
Since some month I was operating successfully a redmine:4.1.1 container with [THIS](https://github.com/karthickmadhiazhagan/a_common_libs) version of the a-common-libs from RMPlus

I pulled the new version 4.1.2 to test, after the a-common-libs plugin is in redmine plugins folder, I can successfull run bundle install and rake redmine:plugins:migrate without errors.
But after a restart from the container, the containers starts but shows in frontend only an error 500.
Until yet I cannot see any log entries regarding this, when I remove the plugin, redmine starts again correct.

Same with new redmine:4.2.0

And the biggest confused thing, I pulled again the 4.1.1 version after my tests and see, same error now also here...

So redmine 4.1.1 was working until my last steps, but in a new image and docker 4.1.1 container its not working?
Perhaps a ruby/rake version thing?

My newest tests was with all 3 versions and complete blank redmine instances, so without my database, files and templates. Also without any other plugins. All with same issue, when the a-common-libs is in plugins folder i get the error 500, when its removed it works...

Another user of redmine without docker said, that all works for him?

What can I do do get more useful information?

Greets

**Comment by RolandSM** [comment]
Latest Log:
`[2021-04-18 08:10:38] INFO  WEBrick 1.6.1
[2021-04-18 08:10:38] INFO  ruby 2.7.3 (2021-04-05) [x86_64-linux]
[2021-04-18 08:10:38] INFO  WEBrick::HTTPServer#start: pid=1 port=3000
173.18.0.1 - - [18/Apr/2021:08:10:44 UTC] "GET /login?back_url=https%3A%2F%2Ftestredmine.TEST.de%2Fissues%2F2453 HTTP/1.1" 500 648
https://testredmine.TEST.de/projects/support/issues -> /login?back_url=https%3A%2F%2Ftestredmine.TEST.de%2Fissues%2F2453`

**Comment by tianon** [comment]
Sorry for the delay -- any chance this is related to https://github.com/karthickmadhiazhagan/a_common_libs/issues/1? (The logs you've provided are pretty sparse -- 500 just means there was an issue and doesn't tell us anything about what the issue is.)

For more/better help, I'd suggest trying a dedicated support forum, such as [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
