### ISSUE TITLE
Can't get log

### ISSUE THREAD

**Issue by orzel** [docker-library/redmine#243]
Inside the container, the log/ directory is there, but empty. I would expect a file 'production.log'. I checked the config/* files, but can't see anything that would prevent the log creation.
Permissions on log/ seems ok to me: it belongs to redmine:redmine, as all other directories in /usr/src/redmine. That's also the user running the application server.

I can get docker log with 'docker logs -f my_instance', but if I reproduce the problem i only see the following line:
172.17.0.1 - - [06/May/2021:09:22:34 UTC] "GET /projects/xxx HTTP/1.0" 500 648

Which is probably the web line, but there's no backtrace or other useful information to debug this 'error 500'.

The webpage displays the usual redmine "error 500" text.

**Comment by wglambert** [comment]
The logs are sent to `stdout` (so that they show in `docker logs`) 
https://github.com/docker-library/redmine/blob/3a41d66499222d90f2f4207c7f6dafd38f4001c5/4.2/Dockerfile#L53-L54

Maybe the level of logging could be edited, like with `config.log_level` but I can't seem to find documentation on it, just discussions and forum posts about it

**Comment by kaedeair** [comment]
> The logs are sent to `stdout` (so that they show in `docker logs`)
> https://github.com/docker-library/redmine/blob/3a41d66499222d90f2f4207c7f6dafd38f4001c5/4.2/Dockerfile#L53-L54
> 
> Maybe the level of logging could be edited, like with `config.log_level` but I can't seem to find documentation on it, just discussions and forum posts about it

I find `config.log_level = :debug` in config/additional_environment.rb.example
