### ISSUE TITLE
4.2.4/4.1.6

### ISSUE THREAD

**Issue by pcworld** [docker-library/redmine#256]
4.2.4 and 4.1.6 [have been released](https://www.redmine.org/news/134), but so far they haven't been added to https://www.redmine.org/releases/ which is [used by update.sh](https://github.com/docker-library/redmine/blob/60cb32bd00c7ecbea747853b067e236cfc56db9d/update.sh#L18). If they aren't added there soon, the docker image should be updated manually with [the links from the "Download" page](https://redmine.org/projects/redmine/wiki/Download).

**Comment by tianon** [comment]
Thanks for the heads up!

@marius-balteanu hopefully you can forgive this ping :bow: :heart:

I was wondering if the new security updates not existing on https://www.redmine.org/releases/ is intentional or just an oversight? (This is the first release where that's been the case :see_no_evil:)

Thanks for your work!

**Comment by marius-balteanu** [comment]
No problem! You can always ping me if you need!

From a technical reason, we cannot upload them until next week, I've added a note to the news.

**Comment by tianon** [comment]
Ah, thanks so much!  We'll adjust accordingly. :+1:

**Comment by marius-balteanu** [comment]
Do you want to drop a comment here as well after we have them uploaded?
