### ISSUE TITLE
After upgrade: Container does not start, if plugins are installed with native extensions

### ISSUE THREAD

**Issue by carstencodes** [docker-library/redmine#331]
Hi,

after updating to a new version (redmine 5.1.2, bookworm), the container keeps restarting because one of the plugins I installed requires the bigdecimal gem. This is a native extension and hence must be compiled in the container.

My current workaround is:

- Replace the entrypoint with the following script:

```shell
#!/bin/sh

set -e

apt-get update && apt-get install -y --no-install recommends build-essential

/docker-entypoint.sh rails server -b 0.0.0.0
```

Is it possible to add build-essential to the standard image?

Regards

Carsten

**Comment by tianon** [comment]
Unfortunately, we have no intention of adding build tools to the standard images (primarily because they are not necessary for running Redmine itself, and if we add them, users who do _not_ need them have no way to remove them).

I would suggest making yourself a very small `Dockerfile` which pre-installs the dependencies you need (including `gem install`, which will speed up your container runtime), and either automating rebuilds of that or using `docker compose`'s functionality to build from a `Dockerfile` instead of deploying an image directly.

**Comment by carstencodes** [comment]
Thanks for the quick reply.

I am using a notification client (watchttower), that looks for new revisions of the image. I would loose this feature, as building a new image would remove the reference to this image.

My workaround is fine and working, but the other thing would be more comfortable.
