### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by lupa18** [docker-library/redmine#36]
Hello ! 
Host server has the correct time, container also, via adding this volume: 
- /etc/localtime:/etc/localtime:ro

but... redmine is registering one hour difference, between each change is registered and real time here in our country. 

I followed some instructions changing config/application.rb file but don't work. References: 
- https://www.redminecrm.com/boards/12/topics/1456-contacts-and-deals-notes-are-added-in-incorrect-time-zone
- https://github.com/jbbarth/redmine_drafts/pull/22

Is it possible that SO timezone don't match with ruby timezone, I mean is not available here:
`bundle exec rake time:zones:all`

and for that reason It doesn't displayed correctly?

Can anyone help me to find what is happening?

**Comment by theblackhole** [comment]
Hi !
Have you tried the TZ environment variable ? See : https://github.com/docker/docker/issues/12084#issuecomment-160177087

And is it necessary for you to have a container with the same timezone than the host ? Because in my case, the container is set to the default timezone and then if I set the wanted timezone in redmine, it works fine ! :smiley:

**Comment by lupa18** [comment]
Thanks, I would try, and tomorrow can have feedback.

**Comment by tianon** [comment]
Closing since this is a configuration question and appears to be resolved. :+1:
