### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by chuckyblack** [docker-library/redmine#38]
I use passeger version.
When I upload larger file (~2MB) I'll get "Request Entity Too Large" message.
I would set up client_max_body_size in nginx.conf normally, but how can I set up this on docker container?

**Comment by yosifkit** [comment]
The passenger based container does not have Nginx since we use passenger standalone, but I don't see anything in their [documentation](https://www.phusionpassenger.com/library/config/standalone/reference/) about `max_body`.  The only related item, `memory-limit`, is unlimited by default.  Are you running an Nginx in front of redmine?

**Comment by chuckyblack** [comment]
Yes, I'm running nginx in front of redmine and I forgot restart nginx after changing it's conf.
Everything is ok now.
Thanks for tip.
