### ISSUE TITLE
REDMINE_NO_DB_MIGRATE, should be default

### ISSUE THREAD

**Issue by hopewise** [docker-library/redmine#55]
As in the docs:

> Just set the variable to a non-empty string like 1 or true and the migrate script will not automatically run on container start.

This should be the default, the container should not migrate data when restarted unless I deliberately set a var like `REDMINE_DB_MIGRATE` to true

I've been using this lovely image in my company, all teams were adding their tasks in the container, until I restarted the container by mistake 😢  All data was removed by migration  😿 !

**Comment by tianon** [comment]
That's really odd!  The database migration code shouldn't remove any data AFAIK. :cry:

Are you using an external database (PostgreSQL/MySQL), or are you just using SQLite?  If external, did the database container/volume get recreated?  If SQLite, where is the SQLite database file being stored (in a persistent volume, anonymous volume, or ephemeral container storage)?

**Comment by hopewise** [comment]
I am not using external database, but only within the same container, using the default db in the container.

Try to create a container using internal database, create simple project. then, simply restart the container, and you will lose all data.. 🌊

**Comment by arthur-tacca** [comment]
Are you sure you didn't recreate, rather than restart, the container? For example, if you're using Docker Compose, and you change something about the service (such as one of the environment variables) then the container will be recreated. If you do this then all the files in the container will be deleted, including the database if you're using SQLite (unless you have mapped the directory it is in as @tianon said). In any case, if you are using the container for anything other than testing then you should, of course, be backing up the database (and attachment files).

**Comment by wglambert** [comment]
I would find that the issue isn't caused by `REDMINE_NO_DB_MIGRATE` but instead an oversight of not persisting the data through a volume or bind mount.

https://docs.docker.com/storage/storagedriver/
>The files won’t be persisted after the container stops, and both read and write speeds are low.

If when you started the container from it being offline, and it has a new ID: then it's a new container and wasn't stopped. Running `docker container stop` or `restart` will keep the data in the 'container' layer

I'm going to prune the issue for now unless you can provide a reproducible for replicating this issue
