### ISSUE TITLE
Having trouble changing the nginx config file permanently

### ISSUE THREAD

**Issue by seccentral** [docker-library/redmine#58]
Hey, i need to serve redmine at a subdir and that implies changing nginx's config but the problem is this file seems to be generated automatically by something somewhere, resides in a randomly generated /tmp subdir  and i have no idea how to make my changes permanent. 

what i have is a docker composition that exposes port 3000 on the docker host. 
This docker host runs it's own production standalone debian jessie packaged nginx that has nothing to do with docker whatsoever and i want it to rev proxy the dockerized redmine at mywebsite.com/redmine 

Really lost here

**Comment by eddiriarte** [comment]
hi @seccentral ,

just trying to use a custom(permanent) nginx.conf (I need CORS-Support for API)

this is what I did:

- create a `nginx.conf.erb` file locally, and adapt it to your needs,  see https://www.phusionpassenger.com/library/config/standalone/intro.html#nginx-configuration-template
- use `volumes` to put the local file into the container
- adapt the `command`/`CMD` from `passenger start` to `passenger start --nginx-config-template /path/to/conf/nginx.conf.erb`, see https://docs.docker.com/compose/compose-file/#command

this should do it!!  ...anyway seems to be faulty... my container is restarting every 5 seconds :(

have you found an alternative solution to this?

**Comment by seccentral** [comment]
Hey I really forgot. this is one year ago

**Comment by wglambert** [comment]
If you wanted to go full docker you could run nginx or haproxy with redmine on the same network and then just edit the conf. If you want to be extra lazy nginx can reload the conf with `nginx -s reload`, with haproxy you'd need to mount it.

nginx in docker uses `default.conf` in `/etc/nginx/conf.d/`

Since this is a usability question, not related to redmine but to nginx on a host, I'm going to close.

You could try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
