### ISSUE TITLE
using fixed host name for mysql and postgresql does not work

### ISSUE THREAD

**Issue by owenhaynes** [docker-library/redmine#6]
using host=mysql or host=postgresql does not work when you are using a kubernetes environment, should take it from an env such as host=$MYSQL_PORT_3306_TCP

**Comment by aborilov** [comment]
The same problem here

**Comment by yosifkit** [comment]
The reason for using a fixed name rather than the value of that environment variable is for container restarts.  The env contains the IP address of the mysql container; if that container restarts (`docker stop/start`) and gets a new IP, the variable won't get updated, but `/etc/hosts` does.  We could instead use the `MYSQL_NAME`/`POSTGRES_NAME` and just pull off the other container's name after the last slash. Something like this?

```diff
-			if [ "$MYSQL_PORT_3306_TCP" ]; then
+			if [ "$MYSQL_NAME" ]; then
				adapter='mysql2'
-				host='mysql'
+				host="${MYSQL_NAME##*/}"
```

**Comment by aborilov** [comment]
Of course we don't need container IP there, we need something like in WordPress:
```
if [ -n "$MYSQL_PORT_3306_TCP" ]; then
		if [ -z "$WORDPRESS_DB_HOST" ]; then
			WORDPRESS_DB_HOST='mysql'
```

**Comment by jgracin** [comment]
Hi! Are there any plans for the new release containing the commit by brainsam?  We need this to run redmine with a non-containerized Postgres.
