### ISSUE TITLE
Three times apt-get update && apt-get install

### ISSUE THREAD

**Issue by saschalalala** [docker-library/redmine#70]
I just used this Dockerfile as a starter for a redmine installation with another plugin. I am no docker expert or something, but isn't it kind of insane to have apt-get update && apt-get install (some packages) running three times instead of just one time?

**Comment by Moghedrin** [comment]
Not insane at all, in fact. Due to the behavior of Docker's caching, it is very rare that ALL of these will be run when we rebuild the image after the first time.

Most often, this image gets rebuilt as a result of a simple version bump for Redmine, which means that the layers prior to `ENV REDMINE_VERSION 3.x.x` are reused.
