### ISSUE TITLE
Redmine 3.3.3 : ERROR Failed to build gem native extension

### ISSUE THREAD

**Issue by tifennlegoff** [docker-library/redmine#81]
Hi,
We have trouble during startup of redmine:3.3.3 (I put all informations on docker-redmine.txt file)
(We haven't this problem the last week.)

Installing rack-raw-upload 1.1.1
The latest bundler is 1.15.2, but you are currently running 1.15.1.
To update, run `gem install bundler`
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/ffi-1.9.18/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20170719-8-95386w.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

[docker-redmine.txt](https://github.com/docker-library/redmine/files/1158553/docker-redmine.txt)

We use docker v1.62 on Debian 8.8 (amd64).

Thanks,
Tifenn LE GOFF

**Comment by yosifkit** [comment]
Please update to 3.3.4.  We have changed the image to no longer need to `bundle install` on startup (https://github.com/docker-library/redmine/pull/80).  Related issue https://github.com/docker-library/redmine/issues/78.

**Comment by tifennlegoff** [comment]
Hi,
Thanks for your answer. We had stayed with 3.3.3 version because of problems with mysql2 gems module (container doesn't start).

Now with 3.3.4 version, we have another issue, we cannot install plugins, when I start container, I have this: 
An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.

I haven't this issue without volume option to mount /usr/src/redmine/plugins in a local place. 


If I connect to the docker with docker exec -it redmine-bis bash, I have this same issue if I run "bundle install". 

But, if I run "apt-get update && apt-get install -y supervisor logrotate nginx mysql-server imagemagick \
       subversion git cvs bzr mercurial rsync ruby2.1 locales \
       gcc g++ make patch pkg-config ruby2.1-dev libc6-dev \
       libmysqlclient18 libpq5 libyaml-0-2 libcurl3 libssl1.0.0 \
       libxslt1.1 libffi6 zlib1g"

After this, "bundle install" and "bundle exec rack"  works but i'm still blocked when the container restart. 

I put all commands in redmine.txt file.
[redmine.txt](https://github.com/docker-library/redmine/files/1183446/redmine.txt)


Do you know how can I fix this ?

Thanks,
Tifenn LE GOFF

**Comment by yosifkit** [comment]
Sorry for the slow reply. :bowing_man:

This isn't really specific to the `redmine` image, but is a general help question since it is about using a plugin that happens to require the `ffi` gem that has to be built. I don't know why it would have worked previously, since the 3.3 image has not included build dependencies.  Most likely you need to install its dependencies in a Dockerfile and use the new image. But do not install `ruby2.1`, `ruby2.1-dev`, or anything that will pull them in since that might override or conflict with the ruby installed from source in the base `ruby:2.2` image.  Something like the following:

```Dockerfile
FROM redmine:3.3
# this version will get you a smaller image in the end
# but it requires you to install and remove all the build dependencies whenever the plugins change
# which is not great if that is what you are developing on
# this is a better setup for production to ensure a minimal set of installed packages in the image
COPY my-plugins/ ./plugins/
RUN apt-get update \
	&& apt-get install -y gcc g++ make libffi6 \
	&& bundle install \
	&& apt-get purge -y --auto-remove gcc g++ make \
	&& rm -rf /var/lib/apt/lists/*


# use this instead for development (and bind mount in your plugins like you have on your docker run line)
FROM redmine:3.3
RUN apt-get update \
	&& apt-get install -y gcc g++ make libffi6 \
	&& rm -rf /var/lib/apt/lists/*
```

You might find better response to general questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
